spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.152.100:3306/rb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: iBoLXiROqopTUT8N8IoQbo2nsn/pXh+cUOpwnl4ziVH2i6L/QLq869lrwZnDMQkWu3MX6uwBQDWeSQwqpUALSw==
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJYUsUiFO1ERsg0N5BzrJMaewCd4//hSked5Rr07f7ZVKMiQ0YxsGrQo72/6/Kxx4mWgW8RNLqNRpHeGCHgdJNUCAwEAAQ==
      initial-size: 5 # 初始化连接池大小
      min-idle: 5 # 最小连接池数量
      max-active: 20 # 最大连接池数量
      max-wait: 60000 # 连接时最大等待时间（单位：毫秒）
      test-while-idle: true # 连接空闲时是否执行检查
      time-between-eviction-runs-millis: 60000 # 配置多久进行一次检测，检测需要关闭的连接（单位：毫秒）
      min-evictable-idle-time-millis: 300000 # 配置一个连接在连接池中最小生存的时间（单位：毫秒）
      max-evictable-idle-time-millis: 900000 # 配置一个连接在连接池中最大生存的时间（单位：毫秒）
      validation-query: select 1 from dual # 配置测试连接是否可用的查询 sql
      test-on-borrow: false # 连接从连接池获取时是否测试连接的可用性
      test-on-return: false # 连接返回连接池时是否测试连接的可用性
      pool-prepared-statements: false # 是否缓存 PreparedStatement，默认为 false
      web-stat-filter:
        enabled: true # 用于配置 Druid 的 Web 监控功能。在这里，enabled 表示是否开启 Web 监控功能。如果设置为 true，就可以通过浏览器访问 Druid 的监控页面
      stat-view-servlet: # 配置 Druid 的监控后台访问路径、登录用户名和密码
        enabled: true
        url-pattern: /druid/* # 配置监控后台访问路径
        login-username: admin # 配置监控后台登录的用户名、密码
        login-password: admin
      filter: # 用于配置 Druid 的过滤器，包括统计过滤器和防火墙过滤器
        config:
          enabled: true
        stat:
          enabled: true # 配置 Druid 的统计过滤器。enabled 表示是否开启统计功能
          log-slow-sql: true # 开启慢 sql 记录
          slow-sql-millis: 2000 # 若执行耗时大于 2s，则视为慢 sql
          merge-sql: true # 表示是否开启 SQL 合并功能
        wall: # 配置 Druid 的防火墙过滤器。防火墙用于防止 SQL 注入攻击
          config:
            multi-statement-allow: true # 表示是否允许执行多条 SQL 语句
  data:
    redis:
      database: 0 # Redis 数据库索引（默认为 0）
      host: 192.168.152.100 # Redis 服务器地址
      port: 6379
      password: 123456
      timeout: 5s # 读超时时间
      connect-timeout: 5s # 链接超时时间
      lettuce:
        pool:
          max-active: 200 # 连接池最大连接数
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接



logging:
  level:
    com.lateautumncoder.rbauth.domain.mapper: debug


